(() => {
'use strict';
const D=(description,ideal,participant,mobile)=>({description,ideal,participant,mobile});
window.H5P_CATALOG={
'H5P.Accordion':D('Organiza información en secciones desplegables.','Procedimientos, preguntas frecuentes, microcontenidos y teoría por bloques.','Abre y cierra secciones según lo que necesita consultar.','Excelente'),
'H5P.AdventCalendar':D('Presenta retos o contenidos distribuidos como un calendario.','Campañas, retos diarios y aprendizaje distribuido en varios días.','Abre casillas para descubrir contenidos o actividades.','Bueno'),
'H5P.Agamotto':D('Permite recorrer varias imágenes superpuestas con un deslizador.','Comparar etapas, cambios, capas o antes/después.','Mueve el control para cambiar progresivamente de imagen.','Bueno'),
'H5P.ARScavenger':D('Crea una búsqueda con realidad aumentada.','Recorridos físicos, localización de elementos y actividades situadas.','Usa cámara y dispositivo para localizar objetivos.','Especializado'),
'H5P.ArithmeticQuiz':D('Genera ejercicios rápidos de cálculo.','Práctica repetitiva de operaciones y agilidad numérica.','Resuelve operaciones y recibe respuesta inmediata.','Excelente'),
'H5P.Audio':D('Reproduce audio dentro del contenido H5P.','Instrucciones, testimonios, ejemplos sonoros y narraciones.','Escucha, pausa y reproduce el recurso.','Excelente'),
'H5P.AudioRecorder':D('Permite grabar la voz del participante.','Respuestas orales, reflexión verbal y evidencias breves.','Activa el micrófono, graba y revisa su audio.','Bueno'),
'H5P.BranchingScenario':D('Construye escenarios ramificados en los que cada decisión conduce a consecuencias distintas.','Toma de decisiones, emergencias, dilemas y estudio de casos.','Elige qué hacer y avanza por rutas diferentes.','Muy bueno'),
'H5P.Chart':D('Presenta datos mediante gráficos.','Indicadores, tendencias, comparaciones y resultados cuantitativos.','Interpreta visualmente la información.','Bueno'),
'H5P.Collage':D('Combina varias imágenes en una composición.','Galerías, ejemplos, evidencias y síntesis visuales.','Explora una composición de imágenes relacionadas.','Bueno'),
'H5P.Column':D('Organiza varios bloques H5P en una página vertical.','Microlecciones completas que mezclan texto, imágenes y preguntas.','Avanza verticalmente por una secuencia de contenidos.','Excelente'),
'H5P.Cornell':D('Guía la toma de notas con el método Cornell.','Estudio guiado, síntesis y reflexión.','Registra notas, ideas clave y resumen.','Bueno'),
'H5P.CoursePresentation':D('Crea una presentación por diapositivas con interacciones integradas.','Lecciones visuales y explicaciones secuenciales.','Avanza por diapositivas y responde actividades.','Medio-bueno'),
'H5P.Crossword':D('Genera un crucigrama a partir de pistas.','Repaso de vocabulario y terminología técnica.','Lee pistas y completa palabras cruzadas.','Bueno'),
'H5P.Dialogcards':D('Muestra tarjetas de estudio con frente y reverso.','Definiciones, señales, equipos y memorización activa.','Piensa la respuesta y voltea la tarjeta.','Excelente'),
'H5P.Dictation':D('Reproduce audio para escribir lo escuchado.','Escucha activa, idiomas e instrucciones verbales.','Escucha fragmentos y escribe la respuesta.','Bueno'),
'H5P.DocumentationTool':D('Guía la construcción de un documento paso a paso.','Planes, análisis, informes y productos escritos.','Completa secciones y construye un documento final.','Medio'),
'H5P.DragQuestion':D('Permite arrastrar elementos a zonas o categorías.','Clasificar objetos, ubicar riesgos, EPP, partes de equipos o procesos.','Arrastra cada elemento a la zona que considera correcta.','Bueno'),
'H5P.DragText':D('Arrastra palabras o frases a espacios dentro de un texto.','Completar frases, ordenar conceptos y comprobar relaciones.','Arrastra palabras al espacio correspondiente.','Muy bueno'),
'H5P.Essay':D('Solicita una respuesta abierta con apoyo de palabras clave.','Argumentación, reflexión y análisis breve.','Redacta una respuesta libre.','Medio'),
'H5P.Blanks':D('Presenta frases o textos con espacios por completar.','Conceptos, procedimientos y terminología.','Escribe la palabra o expresión que falta.','Excelente'),
'H5P.FindMultipleHotspots':D('Pide localizar varios puntos correctos dentro de una imagen.','Inspecciones visuales, detección de peligros y reconocimiento de elementos.','Toca todas las zonas que cumplen la condición.','Muy bueno'),
'H5P.ImageHotspotQuestion':D('Pide localizar un punto correcto dentro de una imagen.','Identificación visual de un elemento concreto.','Toca el lugar donde cree que está la respuesta.','Muy bueno'),
'H5P.FindTheWords':D('Crea una sopa de letras.','Vocabulario, conceptos clave y repaso ligero.','Busca y marca palabras en una cuadrícula.','Bueno'),
'H5P.Flashcards':D('Presenta tarjetas con pregunta o imagen y respuesta.','Memorización y reconocimiento de conceptos.','Observa, responde y comprueba.','Excelente'),
'H5P.GameMap':D('Organiza contenidos como un recorrido por un mapa gamificado.','Misiones, rutas de aprendizaje y retos narrativos.','Avanza por puntos del mapa y completa retos.','Bueno'),
'H5P.GuessTheAnswer':D('Pide anticipar una respuesta antes de revelarla.','Predicción y activación de conocimientos previos.','Piensa la respuesta y luego la revela.','Excelente'),
'H5P.IFrameEmbed':D('Inserta un recurso web externo mediante iframe.','Simuladores, herramientas y recursos externos compatibles.','Interactúa con el sitio incrustado.','Variable'),
'H5P.ImageHotspots':D('Coloca puntos interactivos sobre una imagen para revelar información.','Equipos, mapas, instalaciones y escenas de riesgo.','Toca hotspots para descubrir información.','Excelente'),
'H5P.ImageJuxtaposition':D('Compara dos imágenes con una barra deslizante.','Antes/después, mejoras y comparaciones visuales.','Desliza la separación entre dos imágenes.','Excelente'),
'H5P.ImagePair':D('Crea un ejercicio para emparejar imágenes relacionadas.','Asociar señal-equipo, peligro-control u objetos relacionados.','Selecciona imágenes que forman una pareja.','Muy bueno'),
'H5P.ImageSequencing':D('Pide ordenar imágenes en una secuencia correcta.','Procedimientos, pasos y cronologías visuales.','Arrastra imágenes hasta ordenar la secuencia.','Bueno'),
'H5P.ImageSlider':D('Muestra una galería de imágenes navegable.','Ejemplos, casos, evidencias y secuencias visuales.','Avanza o desliza entre imágenes.','Excelente'),
'H5P.InformationWall':D('Presenta bloques de información en una pared visual.','Colecciones de recursos y conceptos explorables.','Explora diferentes piezas de información.','Bueno'),
'H5P.InteractiveBook':D('Crea un libro por páginas o capítulos combinando varios tipos H5P.','Unidades completas, guías interactivas y cursos estructurados.','Navega por capítulos y realiza actividades.','Muy bueno'),
'H5P.InteractiveVideo':D('Añade preguntas y otras interacciones dentro de un video.','Videos formativos con comprobaciones durante la reproducción.','Ve el video y responde en momentos específicos.','Muy bueno'),
'H5P.KewArCode':D('Genera códigos QR para acceder a recursos.','Vincular espacios físicos, carteles o equipos con contenido digital.','Escanea el código con el teléfono.','Excelente'),
'H5P.MarkTheWords':D('Pide seleccionar palabras o expresiones correctas dentro de un texto.','Reconocer peligros, conceptos, errores o elementos clave.','Toca las palabras que cumplen la condición.','Excelente'),
'H5P.MemoryGame':D('Crea un juego de memoria para encontrar pares.','Repaso gamificado de imágenes, señales y conceptos.','Voltea tarjetas y busca parejas.','Excelente'),
'H5P.MultiMediaChoice':D('Presenta opciones de respuesta con imágenes, audio u otros medios.','Preguntas visuales o auditivas.','Elige la alternativa multimedia correcta.','Muy bueno'),
'H5P.MultiChoice':D('Crea preguntas con varias alternativas y una o más respuestas correctas.','Evaluación rápida, casos breves y comprobación de comprensión.','Lee, selecciona alternativas y recibe retroalimentación.','Excelente'),
'H5P.PersonalityQuiz':D('Calcula un perfil final según las respuestas.','Autodiagnósticos y actividades lúdicas.','Responde opciones y recibe un resultado.','Excelente'),
'H5P.QuestionSet':D('Agrupa varias preguntas H5P en una evaluación única.','Quizzes, evaluaciones formativas y conjuntos mixtos.','Responde una serie de preguntas y obtiene resultado global.','Excelente'),
'H5P.Questionnaire':D('Recoge respuestas a varias preguntas tipo encuesta.','Opiniones, diagnósticos y autoevaluaciones.','Completa un cuestionario y envía respuestas.','Excelente'),
'H5P.SingleChoiceSet':D('Presenta una serie de preguntas de una sola respuesta correcta.','Microlearning y chequeos rápidos.','Elige una respuesta y avanza a la siguiente.','Excelente'),
'H5P.SortParagraphs':D('Pide ordenar párrafos o pasos.','Procedimientos, secuencias y prioridades.','Arrastra bloques hasta el orden correcto.','Muy bueno'),
'H5P.SpeakTheWords':D('Solicita una respuesta oral mediante reconocimiento de voz.','Pronunciación y respuestas verbales breves.','Habla al micrófono para responder.','Variable'),
'H5P.SpeakTheWordsSet':D('Agrupa varias actividades de respuesta por voz.','Práctica oral en serie.','Pronuncia varias respuestas usando el micrófono.','Variable'),
'H5P.StructureStrip':D('Ofrece una plantilla visual para organizar una respuesta.','Planificación, redacción guiada y organización de ideas.','Completa apartados según una estructura.','Bueno'),
'H5P.Summary':D('Pide elegir afirmaciones correctas para construir un resumen.','Consolidación de ideas clave y cierre de temas.','Selecciona la afirmación correcta en cada paso.','Excelente'),
'H5P.Timeline':D('Muestra eventos en una línea temporal.','Historia, evolución normativa y cronologías.','Explora eventos ordenados en el tiempo.','Bueno'),
'H5P.TrueFalse':D('Plantea una afirmación para decidir si es verdadera o falsa.','Mitos, conceptos puntuales y chequeos rápidos.','Elige verdadero o falso y recibe retroalimentación.','Excelente'),
'H5P.TwitterUserFeed':D('Muestra publicaciones de un usuario de X/Twitter.','Integrar un feed social en contenidos.','Consulta publicaciones incrustadas.','Variable'),
'H5P.VirtualTour':D('Crea un recorrido inmersivo con imágenes 360° y hotspots.','Recorridos de instalaciones, inspecciones y reconocimiento espacial.','Explora escenas 360° y navega entre puntos.','Muy bueno')
};

window.H5P_NAMES_ES={
'H5P.Accordion':'Acordeón',
'H5P.AdventCalendar':'Calendario de retos',
'H5P.Agamotto':'Secuencia progresiva de imágenes',
'H5P.ARScavenger':'Búsqueda con realidad aumentada',
'H5P.ArithmeticQuiz':'Quiz de cálculo',
'H5P.Audio':'Audio',
'H5P.AudioRecorder':'Grabadora de audio',
'H5P.BranchingScenario':'Escenario ramificado',
'H5P.Chart':'Gráfico',
'H5P.Collage':'Collage de imágenes',
'H5P.Column':'Página de contenidos',
'H5P.Cornell':'Notas Cornell',
'H5P.CoursePresentation':'Presentación interactiva',
'H5P.Crossword':'Crucigrama',
'H5P.Dialogcards':'Tarjetas de diálogo',
'H5P.Dictation':'Dictado',
'H5P.DocumentationTool':'Herramienta de documentación',
'H5P.DragQuestion':'Arrastrar y soltar',
'H5P.DragText':'Arrastrar palabras',
'H5P.Essay':'Respuesta abierta',
'H5P.Blanks':'Completar espacios',
'H5P.FindMultipleHotspots':'Encontrar varios puntos en una imagen',
'H5P.ImageHotspotQuestion':'Encontrar un punto en una imagen',
'H5P.FindTheWords':'Sopa de letras',
'H5P.Flashcards':'Tarjetas de estudio',
'H5P.GameMap':'Mapa de juego',
'H5P.GuessTheAnswer':'Adivina la respuesta',
'H5P.IFrameEmbed':'Recurso web incrustado',
'H5P.ImageHotspots':'Puntos interactivos en una imagen',
'H5P.ImageJuxtaposition':'Comparar dos imágenes',
'H5P.ImagePair':'Emparejar imágenes',
'H5P.ImageSequencing':'Ordenar imágenes',
'H5P.ImageSlider':'Galería de imágenes',
'H5P.InformationWall':'Muro de información',
'H5P.InteractiveBook':'Libro interactivo',
'H5P.InteractiveVideo':'Video interactivo',
'H5P.KewArCode':'Código QR',
'H5P.MarkTheWords':'Marcar palabras',
'H5P.MemoryGame':'Juego de memoria',
'H5P.MultiMediaChoice':'Elección multimedia',
'H5P.MultiChoice':'Opción múltiple',
'H5P.PersonalityQuiz':'Quiz de perfil',
'H5P.QuestionSet':'Conjunto de preguntas',
'H5P.Questionnaire':'Cuestionario / encuesta',
'H5P.SingleChoiceSet':'Preguntas de respuesta única',
'H5P.SortParagraphs':'Ordenar párrafos',
'H5P.SpeakTheWords':'Responder con la voz',
'H5P.SpeakTheWordsSet':'Serie de respuestas con voz',
'H5P.StructureStrip':'Estructura guiada',
'H5P.Summary':'Construir un resumen',
'H5P.Timeline':'Línea de tiempo',
'H5P.TrueFalse':'Verdadero o falso',
'H5P.TwitterUserFeed':'Feed de X / Twitter',
'H5P.VirtualTour':'Recorrido virtual 360°'
};
window.H5P_CATALOG_FALLBACK=(lib)=>({description:'Actividad H5P disponible en el catálogo local. La aplicación puede utilizar su ficha pedagógica aunque todavía no tenga una descripción específica.',ideal:'Usos definidos por las capacidades de esta librería.',participant:'Interactúa según el tipo de contenido configurado.',mobile:'Debe probarse en móvil antes de publicar.'});
})();
