(() => {
  'use strict';
  const entries=[
    {"keys": ["accordion"], "name": "Accordion", "what": "Organiza información en secciones desplegables que se abren y cierran.", "ideal": "Microcontenidos, procedimientos, preguntas frecuentes y teoría por bloques.", "participant": "Toca cada encabezado para revelar la información cuando la necesita.", "mobile": "Excelente. Muy cómodo en pantallas pequeñas."},
    {"keys": ["advent calendar", "adventcalendar"], "name": "Advent Calendar", "what": "Presenta contenidos o retos que se desbloquean como un calendario.", "ideal": "Campañas de aprendizaje, retos diarios y secuencias de varios días.", "participant": "Abre casillas o días para descubrir contenido progresivamente.", "mobile": "Bueno. Conviene limitar la densidad de elementos."},
    {"keys": ["agamotto"], "name": "Agamotto", "what": "Permite explorar varias imágenes superpuestas mediante un deslizador.", "ideal": "Comparar etapas, cambios, antes/después o capas visuales.", "participant": "Mueve un control para pasar progresivamente entre imágenes.", "mobile": "Bueno con imágenes simples y nítidas."},
    {"keys": ["ar scavenger", "arscavenger", "scavenger"], "name": "AR Scavenger", "what": "Crea búsquedas o recorridos con elementos de realidad aumentada.", "ideal": "Exploraciones físicas, búsqueda de objetos y actividades situadas.", "participant": "Usa el dispositivo para localizar objetivos o marcadores en el entorno.", "mobile": "Especializado: depende de cámara, permisos y compatibilidad."},
    {"keys": ["arithmetic quiz", "arithmeticquiz"], "name": "Arithmetic Quiz", "what": "Genera ejercicios rápidos de cálculo aritmético.", "ideal": "Práctica repetitiva de operaciones y agilidad numérica.", "participant": "Resuelve operaciones y recibe resultados inmediatos.", "mobile": "Excelente."},
    {"keys": ["audio recorder", "audiorecorder"], "name": "Audio Recorder", "what": "Permite grabar la voz directamente desde el dispositivo.", "ideal": "Respuestas orales, pronunciación, reflexión verbal y evidencias breves.", "participant": "Activa el micrófono, graba y revisa su audio.", "mobile": "Bueno, sujeto a permisos de micrófono."},
    {"keys": [" audio ", "h5p audio"], "name": "Audio", "what": "Reproduce un archivo de audio dentro del contenido.", "ideal": "Instrucciones, testimonios, explicaciones y ejemplos sonoros.", "participant": "Escucha, pausa y reproduce el recurso.", "mobile": "Excelente."},
    {"keys": ["branching scenario", "branchingscenario"], "name": "Branching Scenario", "what": "Construye un escenario ramificado donde cada decisión lleva a consecuencias distintas.", "ideal": "Toma de decisiones, emergencias, dilemas y estudios de caso.", "participant": "Elige qué hacer y avanza por rutas diferentes según sus decisiones.", "mobile": "Muy bueno si cada pantalla tiene poco texto."},
    {"keys": ["chart"], "name": "Chart", "what": "Presenta datos mediante gráficos visuales.", "ideal": "Indicadores, comparaciones, tendencias y resultados cuantitativos.", "participant": "Interpreta visualmente los datos mostrados.", "mobile": "Bueno; evita gráficos demasiado densos."},
    {"keys": ["collage"], "name": "Collage", "what": "Combina varias imágenes en una composición visual.", "ideal": "Galerías, evidencias, ejemplos y síntesis visuales.", "participant": "Observa un conjunto de imágenes relacionadas.", "mobile": "Bueno."},
    {"keys": ["column", "page column", "page/column"], "name": "Column / Page", "what": "Organiza varios bloques H5P uno debajo de otro como una página o lección.", "ideal": "Microlecciones que combinan texto, imágenes, preguntas y otros H5P.", "participant": "Avanza verticalmente por una secuencia de contenidos e interacciones.", "mobile": "Excelente cuando se diseña mobile-first."},
    {"keys": ["cornell notes", "cornellnotes"], "name": "Cornell Notes", "what": "Estructura una actividad de toma de notas siguiendo el método Cornell.", "ideal": "Estudio guiado, síntesis y reflexión sobre contenidos.", "participant": "Registra notas, ideas clave y un resumen estructurado.", "mobile": "Bueno; textos largos son más cómodos en tablet o PC."},
    {"keys": ["course presentation", "coursepresentation"], "name": "Course Presentation", "what": "Crea una presentación por diapositivas con contenido e interacciones incrustadas.", "ideal": "Lecciones visuales, explicaciones secuenciales y presentaciones interactivas.", "participant": "Avanza entre diapositivas y responde actividades dentro de ellas.", "mobile": "Medio-bueno; requiere diseños simples y poco contenido por diapositiva."},
    {"keys": ["crossword"], "name": "Crossword", "what": "Genera un crucigrama a partir de definiciones o pistas.", "ideal": "Repaso de conceptos, vocabulario y terminología técnica.", "participant": "Lee pistas y completa palabras cruzadas.", "mobile": "Bueno; crucigramas grandes pueden requerir zoom."},
    {"keys": ["dialog cards", "dialogcards"], "name": "Dialog Cards", "what": "Muestra tarjetas de estudio con una cara inicial y otra con respuesta o explicación.", "ideal": "Conceptos, definiciones, señales, equipos y memorización activa.", "participant": "Piensa la respuesta y voltea la tarjeta para comprobarla.", "mobile": "Excelente."},
    {"keys": ["dictation"], "name": "Dictation", "what": "Reproduce audio para que el participante escriba lo que escucha.", "ideal": "Escucha activa, idiomas y reconocimiento de instrucciones verbales.", "participant": "Escucha fragmentos y escribe la respuesta.", "mobile": "Bueno."},
    {"keys": ["documentation tool", "documentationtool"], "name": "Documentation Tool", "what": "Guía al participante para construir un documento estructurado paso a paso.", "ideal": "Planes, análisis, informes y productos escritos guiados.", "participant": "Completa diferentes apartados y genera un documento final.", "mobile": "Medio; mejor para respuestas breves en teléfono."},
    {"keys": ["drag and drop", "dragquestion"], "name": "Drag and Drop", "what": "Permite arrastrar elementos hacia zonas específicas de una imagen o área.", "ideal": "Clasificar objetos, ubicar riesgos, asociar EPP, partes de equipos o procesos.", "participant": "Arrastra cada elemento hasta la zona que considera correcta.", "mobile": "Bueno si objetos y zonas son grandes."},
    {"keys": ["drag the words", "dragtext"], "name": "Drag the Words", "what": "Convierte palabras o expresiones en elementos que deben arrastrarse a espacios correctos.", "ideal": "Completar frases, ordenar conceptos y verificar relaciones.", "participant": "Arrastra palabras hasta el espacio correspondiente.", "mobile": "Muy bueno con textos cortos."},
    {"keys": ["essay"], "name": "Essay", "what": "Solicita una respuesta abierta y puede ofrecer retroalimentación basada en palabras clave.", "ideal": "Argumentación, reflexión y análisis breve.", "participant": "Redacta una respuesta libre.", "mobile": "Medio; mejor para respuestas cortas en teléfono."},
    {"keys": ["fill in the blanks", "blanks"], "name": "Fill in the Blanks", "what": "Presenta frases o textos con espacios que deben completarse.", "ideal": "Conceptos, procedimientos, terminología y comprobación de comprensión.", "participant": "Escribe la palabra o expresión que falta.", "mobile": "Excelente si las respuestas son breves."},
    {"keys": ["find multiple hotspots", "findmultiplehotspots"], "name": "Find Multiple Hotspots", "what": "Pide localizar varios puntos correctos dentro de una imagen.", "ideal": "Inspecciones visuales, detección de peligros y reconocimiento de elementos.", "participant": "Toca todos los lugares de la imagen que cumplen la condición.", "mobile": "Muy bueno si las zonas objetivo son suficientemente grandes."},
    {"keys": ["find the hotspot", "find hotspot", "findthehotspot"], "name": "Find the Hotspot", "what": "Pide encontrar un único punto o zona correcta dentro de una imagen.", "ideal": "Identificación visual de un elemento concreto.", "participant": "Toca el lugar de la imagen donde cree que está la respuesta.", "mobile": "Muy bueno."},
    {"keys": ["find the words", "findthewords"], "name": "Find The Words", "what": "Crea una sopa de letras con términos que deben localizarse.", "ideal": "Vocabulario, conceptos clave y repaso ligero.", "participant": "Busca y marca palabras dentro de una cuadrícula.", "mobile": "Bueno; mejor con cuadrículas pequeñas."},
    {"keys": ["flashcards", "flashcard"], "name": "Flashcards", "what": "Presenta tarjetas con imagen o pregunta y una respuesta que debe recordarse.", "ideal": "Memorización, reconocimiento de equipos, símbolos y conceptos.", "participant": "Observa la tarjeta, responde mentalmente o escribe y comprueba.", "mobile": "Excelente."},
    {"keys": ["game map", "gamemap"], "name": "Game Map", "what": "Organiza actividades y contenidos como un recorrido por un mapa gamificado.", "ideal": "Misiones, rutas de aprendizaje, retos y cursos con narrativa.", "participant": "Avanza por puntos del mapa y completa retos para progresar.", "mobile": "Bueno; hay que probar navegación y tamaño de los puntos."},
    {"keys": ["guess the answer", "guesstheanswer"], "name": "Guess the Answer", "what": "Presenta una imagen o contenido y pide anticipar una respuesta antes de revelarla.", "ideal": "Predicción, activación de conocimientos previos y curiosidad.", "participant": "Piensa qué cree que es y luego revela la respuesta.", "mobile": "Excelente."},
    {"keys": ["iframe embedder", "iframeembedder", "iframe"], "name": "Iframe Embedder", "what": "Inserta dentro de H5P una página o recurso web externo mediante iframe.", "ideal": "Herramientas externas, simuladores o recursos web compatibles.", "participant": "Interactúa con el recurso incrustado.", "mobile": "Variable; depende de que la web externa sea responsive."},
    {"keys": ["image hotspots", "imagehotspots"], "name": "Image Hotspots", "what": "Coloca puntos interactivos sobre una imagen que revelan información al tocarlos.", "ideal": "Explorar equipos, mapas, instalaciones, máquinas y escenas de riesgo.", "participant": "Toca los puntos para descubrir explicaciones, imágenes u otros recursos.", "mobile": "Excelente si los hotspots tienen buen tamaño táctil."},
    {"keys": ["image juxtaposition", "imagejuxtaposition", "juxtaposition"], "name": "Image Juxtaposition", "what": "Compara dos imágenes mediante una barra deslizante de antes/después.", "ideal": "Cambios, mejoras, controles implementados y comparaciones visuales.", "participant": "Desliza la separación para revelar una u otra imagen.", "mobile": "Excelente."},
    {"keys": ["image pair", "imagepair"], "name": "Image Pair", "what": "Crea un ejercicio para emparejar imágenes relacionadas.", "ideal": "Asociar señal-equipo, peligro-control, objeto-categoría o pares visuales.", "participant": "Selecciona imágenes que forman una pareja correcta.", "mobile": "Muy bueno."},
    {"keys": ["image sequencing", "imagesequencing"], "name": "Image Sequencing", "what": "Pide ordenar imágenes en una secuencia correcta.", "ideal": "Procedimientos, pasos de trabajo y cronologías visuales.", "participant": "Arrastra imágenes hasta colocarlas en el orden correcto.", "mobile": "Bueno con pocas imágenes y elementos grandes."},
    {"keys": ["image slider", "imageslider"], "name": "Image Slider", "what": "Muestra una galería de imágenes navegable.", "ideal": "Ejemplos, casos, evidencias y secuencias visuales.", "participant": "Desliza o avanza entre imágenes.", "mobile": "Excelente."},
    {"keys": ["information wall", "informationwall"], "name": "Information Wall", "what": "Presenta múltiples bloques de información en una pared o panel visual.", "ideal": "Colecciones de recursos, conceptos o contenidos explorables.", "participant": "Explora diferentes piezas de información.", "mobile": "Bueno; debe evitarse demasiada densidad."},
    {"keys": ["interactive book", "interactivebook"], "name": "Interactive Book", "what": "Crea un libro por páginas o capítulos combinando numerosos tipos H5P.", "ideal": "Unidades completas, guías interactivas y cursos estructurados.", "participant": "Navega por capítulos y realiza actividades integradas.", "mobile": "Muy bueno con capítulos cortos y diseño vertical."},
    {"keys": ["interactive video", "interactivevideo"], "name": "Interactive Video", "what": "Añade preguntas, textos, enlaces y otras interacciones dentro de un video.", "ideal": "Videos formativos donde se desea comprobar comprensión durante la reproducción.", "participant": "Ve el video y responde o interactúa en momentos específicos.", "mobile": "Muy bueno si las interacciones se diseñan para pantalla pequeña."},
    {"keys": ["kewar code", "kewarcode", "qr code", "kewar"], "name": "KewAr Code", "what": "Genera códigos QR que enlazan a información o recursos.", "ideal": "Acceso rápido desde espacios físicos, carteles, equipos o materiales impresos.", "participant": "Escanea el código con su teléfono para acceder al recurso.", "mobile": "Excelente."},
    {"keys": ["mark the words", "markthewords"], "name": "Mark the Words", "what": "Pide seleccionar palabras o expresiones correctas dentro de un texto.", "ideal": "Reconocer peligros, conceptos, errores o elementos clave en una frase.", "participant": "Toca las palabras que cumplen la condición indicada.", "mobile": "Excelente."},
    {"keys": ["memory game", "memorygame"], "name": "Memory Game", "what": "Crea un juego de memoria para encontrar pares de tarjetas.", "ideal": "Repaso gamificado de conceptos, imágenes, señales y asociaciones.", "participant": "Voltea tarjetas e intenta recordar dónde está cada pareja.", "mobile": "Excelente con un número moderado de tarjetas."},
    {"keys": ["multimedia choice", "multimediachoice"], "name": "Multimedia Choice", "what": "Presenta opciones de respuesta que pueden incluir imágenes, audio u otros medios.", "ideal": "Preguntas visuales o auditivas y selección entre alternativas multimedia.", "participant": "Elige la opción multimedia que considera correcta.", "mobile": "Muy bueno."},
    {"keys": ["multiple choice", "multichoice"], "name": "Multiple Choice", "what": "Crea preguntas con varias alternativas y una o más respuestas correctas.", "ideal": "Evaluación rápida, escenarios breves, conceptos y comprobación de comprensión.", "participant": "Lee la pregunta, selecciona alternativas y recibe retroalimentación.", "mobile": "Excelente."},
    {"keys": ["personality quiz", "personalityquiz"], "name": "Personality Quiz", "what": "Clasifica respuestas para mostrar un resultado o perfil final.", "ideal": "Autodiagnósticos, estilos, perfiles orientativos y actividades lúdicas.", "participant": "Responde opciones y recibe un resultado según sus elecciones.", "mobile": "Excelente."},
    {"keys": ["question set", "questionset"], "name": "Question Set", "what": "Agrupa varias preguntas H5P en una evaluación o secuencia única.", "ideal": "Quizzes, evaluaciones formativas y conjuntos mixtos de preguntas.", "participant": "Responde una serie de preguntas y obtiene un resultado global.", "mobile": "Excelente si cada pregunta individual es mobile-friendly."},
    {"keys": ["questionnaire"], "name": "Questionnaire", "what": "Recoge respuestas a varias preguntas tipo encuesta o cuestionario.", "ideal": "Opiniones, autoevaluaciones, diagnósticos y recolección de información.", "participant": "Completa varias preguntas y envía sus respuestas.", "mobile": "Excelente."},
    {"keys": ["single choice set", "singlechoiceset"], "name": "Single Choice Set", "what": "Presenta varias preguntas donde solo una alternativa es correcta.", "ideal": "Preguntas rápidas y secuencias de comprobación inmediata.", "participant": "Elige una respuesta y avanza rápidamente a la siguiente.", "mobile": "Excelente."},
    {"keys": ["sort the paragraphs", "sortparagraphs"], "name": "Sort the Paragraphs", "what": "Pide ordenar párrafos, pasos o fragmentos de texto.", "ideal": "Procedimientos, secuencias, prioridades y orden lógico.", "participant": "Arrastra bloques hasta colocarlos en la secuencia correcta.", "mobile": "Muy bueno con bloques cortos."},
    {"keys": ["speak the words set", "speakthewordsset"], "name": "Speak the Words Set", "what": "Agrupa varias actividades de respuesta por voz.", "ideal": "Práctica oral y reconocimiento de expresiones habladas.", "participant": "Pronuncia respuestas usando el micrófono.", "mobile": "Variable según navegador, idioma y reconocimiento de voz."},
    {"keys": ["speak the words", "speakthewords"], "name": "Speak the Words", "what": "Solicita responder oralmente y utiliza reconocimiento de voz.", "ideal": "Pronunciación y respuestas verbales breves.", "participant": "Habla al micrófono para responder.", "mobile": "Variable según navegador, idioma y permisos."},
    {"keys": ["structure strip", "structurestrip"], "name": "Structure Strip", "what": "Proporciona una estructura o plantilla visual para organizar una respuesta.", "ideal": "Guiar redacción, planificación y organización de ideas.", "participant": "Completa apartados siguiendo una estructura predeterminada.", "mobile": "Bueno para entradas breves."},
    {"keys": ["summary"], "name": "Summary", "what": "Presenta grupos de afirmaciones donde el participante selecciona la correcta para construir un resumen.", "ideal": "Consolidar ideas clave y verificar comprensión de un tema.", "participant": "Elige la afirmación correcta en cada paso hasta formar un resumen.", "mobile": "Excelente."},
    {"keys": ["timeline"], "name": "Timeline", "what": "Organiza acontecimientos en una línea de tiempo interactiva.", "ideal": "Historia, evolución normativa, incidentes, hitos y secuencias cronológicas.", "participant": "Recorre fechas y eventos para explorar la secuencia.", "mobile": "Bueno; mantener textos breves mejora el uso móvil."},
    {"keys": ["true false", "truefalse"], "name": "True/False", "what": "Presenta una afirmación para decidir si es verdadera o falsa.", "ideal": "Mitos, conceptos puntuales, verificaciones rápidas y diagnóstico.", "participant": "Selecciona verdadero o falso y recibe retroalimentación.", "mobile": "Excelente."},
    {"keys": ["twitter user feed", "twitteruserfeed", "twitter"], "name": "Twitter User Feed", "what": "Muestra un feed de una cuenta de Twitter/X dentro del contenido.", "ideal": "Seguimiento de publicaciones externas o fuentes sociales.", "participant": "Consulta publicaciones incrustadas de una cuenta.", "mobile": "Variable; depende del servicio externo y sus políticas."},
    {"keys": ["virtual tour 360", "virtualtour", "360"], "name": "Virtual Tour (360)", "what": "Crea un recorrido inmersivo por imágenes 360° con puntos interactivos y navegación entre escenas.", "ideal": "Recorridos de instalaciones, inspecciones, emergencias y reconocimiento espacial.", "participant": "Mueve la vista 360°, explora hotspots y navega entre escenas.", "mobile": "Muy bueno, aunque consume más recursos y funciona mejor en teléfonos recientes."},
  ];
  const normalize=value=>String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').replace(/\s+/g,' ').trim();
  function findGuide(lib){
    const hay=normalize((lib?.title||'')+' '+(lib?.machineName||''));
    let winner=null, winnerScore=-1;
    for(const item of entries){
      for(const key of item.keys){
        const k=normalize(key);
        if(k && hay.includes(k) && k.length>winnerScore){winner=item;winnerScore=k.length;}
      }
    }
    return winner;
  }
  function fallback(lib){
    return {name:lib?.title||lib?.machineName||'Actividad H5P',what:'Actividad H5P compatible con Moodle. La explicación específica todavía no está cargada, pero el generador puede trabajar con su estructura semantics.',ideal:'Uso según la finalidad pedagógica definida por la librería.',participant:'La interacción dependerá de la configuración elegida para esta actividad.',mobile:'Debe probarse en teléfono; la aplicación mantendrá criterios mobile-first.'};
  }
  window.H5PCatalog={entries,findGuide,fallback};
})();
